---
- name: install docker
  hosts: swarm
  sudo: True

  tasks:
    - name: stop docker service
      service: state=stopped name=docker

    - name: copy docker systemd file
      copy:
        src: docker.service.d
        dest: /etc/systemd/system

    - name: update systemd-daemon
      command: systemctl daemon-reload

    - name: enable systemd
      service:
        name: docker.service
        enabled: yes
        state: started
